<!--following code is generated by templates/bottom.inc.php-->
<div id="bottom">
<?php
echo T_("Propulsed by ");
echo "<a href=\"https://sourceforge.net/projects/semanticscuttle/\">SemanticScuttle</a>";

if($GLOBALS['enableWebsiteThumbnails']) {
	// Licence to the thumbnails provider (OBLIGATORY IF YOU USE ARTVIPER SERVICE)
	echo " (<a href=\"http://www.artviper.net\" title=\"artViper designstudio\">thumbnails by artViper designstudio</a>)";
}
?>

</div>

</body>
</html>
